// Maps the first three characters (WMI) to the specific manufacturer or joint venture.
// This mapping is used for brand identification once the VIN is confirmed valid.
export const MANUFACTURERS = {
    /**
     * Africa
     */
    Africa: {
        // South Africa
        'South Africa': {
            'AAA': 'Audi / Volkswagen',
            'AAK': 'FAW',
            'AAM': 'MAN / VW Truck & Bus',
            'AAV': 'Volkswagen',
            'ABJ': 'Mitsubishi / Daimler (Fuso trucks, formerly Colt/Triton pickups by Mercedes-Benz)',
            'ABM': 'BMW',
            'AC5': 'Hyundai (Note: Updated from Mahindra)',
            'ACV': 'Isuzu',
            'ADD': 'UD Trucks',
            'ADM': 'General Motors',
            'ADN': 'Nissan',
            'ADR': 'Renault / Nissan (e.g., Renault Sandero)',
            'ADX': 'Tata',
            'AFA': 'Ford & Samcor',
            'AFB': 'Mazda / Ford (e.g., Mazda BT-50)',
            'AFV': 'Ford',
            'AHH': 'Hino',
            'AHM': 'Honda / Mercedes-Benz (formerly by Mercedes-Benz (1982–2000))',
            'AHT': 'Toyota',
        },

        // Angola
        'Angola': {
            'BAB': 'All Manufacturers',
        },

        // Kenya
        'Kenya': {
            'BF9': 'KIBO Motorcycles',
        },

        // Tunisia
        'Tunisia': {
            'CL9': 'Wallyscar',
        },

        // Egypt
        'Egypt': {
            'DA1': 'Arab American Vehicles',
            'DA4': 'Arab American Vehicles',
            'DAA': 'Fiat',
            'DAB': 'BMW',
        },

        // Morocco
        'Morocco': {
            'DF9': 'Laraki',
        },

        // Madagascar
        'Madagascar': {
            'GA1': 'Renault / SOMACOA',
        },
    },
    /**
     * Asia
     */
    Asia: {
        // Japan
        'Japan': {
            'JD1': 'Daihatsu (car)',
            'JD2': 'Daihatsu (MPV/SUV)',
            'JD4': 'Daihatsu (truck)',
            'JDA': 'Daihatsu',
            'JHA': 'Hino',
            'JHB': 'Hino',
            'JHD': 'Hino',
            'JHF': 'Hino',
            'JHH': 'Hino',
            'JH2': 'Honda (Motorcycle/ATV)',
            'JH3': 'Honda (ATV)',
            'JH4': 'Acura / Honda',
            'JHL': 'Honda (SUV/MPV)',
            'JHM': 'Honda (Car)',
            'JR2': 'Honda (For Isuzu Oasis)',
            'J81': 'Isuzu (For Chevrolet/Geo cars)',
            'J87': 'Isuzu (For Pontiac/Asüna cars)',
            'J8B': 'Isuzu (For Chevrolet commercial trucks)',
            'J8C': 'Isuzu (For Chevrolet commercial trucks)',
            'J8D': 'Isuzu (For GMC commercial trucks)',
            'J8T': 'Isuzu (For GMC commercial trucks)',
            'J8Z': 'Isuzu (For Chevrolet pickup trucks)',
            'JAA': 'Isuzu (Truck)',
            'JAB': 'Isuzu (Car)',
            'JAC': 'Isuzu (SUV)',
            'JAE': 'Isuzu (For Acura SLX)',
            'JAL': 'Isuzu (For Isuzu, Chevrolet & Hino trucks)',
            'JAM': 'Isuzu (Commercial trucks)',
            'JK8': 'Kawasaki (For Suzuki QUV620F UTV)',
            'JKA': 'Kawasaki',
            'JKB': 'Kawasaki',
            'JKS': 'Kawasaki (For Suzuki Marauder/Boulevard motorcycles)',
            'JC0': 'Mazda (For Ford cars)',
            'JC1': 'Mazda (For Fiat 124 Spider)',
            'JC2': 'Mazda (For Ford Courier)',
            'JM0': 'Mazda',
            'JM1': 'Mazda (Car)',
            'JM2': 'Mazda (Truck)',
            'JM3': 'Mazda (MPV/SUV)',
            'JM6': 'Mazda',
            'JM7': 'Mazda',
            'JMZ': 'Mazda',
            'JA3': 'Mitsubishi (Car)',
            'JA4': 'Mitsubishi (MPV/SUV)',
            'JA7': 'Mitsubishi (Truck)',
            'JB3': 'Mitsubishi (For Dodge cars)',
            'JB4': 'Mitsubishi (For Dodge MPV/SUV)',
            'JB7': 'Mitsubishi (For Dodge trucks)',
            'JE3': 'Mitsubishi (For Eagle cars)',
            'JE4': 'Mitsubishi',
            'JJ3': 'Mitsubishi (For Chrysler cars)',
            'JL5': 'Mitsubishi Fuso',
            'JL6': 'Mitsubishi Fuso',
            'JLF': 'Mitsubishi Fuso',
            'JLS': 'Mitsubishi Fuso (For Sterling Trucks 360)',
            'JMA': 'Mitsubishi',
            'JMB': 'Mitsubishi',
            'JMF': 'Mitsubishi',
            'JMY': 'Mitsubishi',
            'JP3': 'Mitsubishi (For Plymouth cars)',
            'JP4': 'Mitsubishi (For Plymouth MPV/SUV)',
            'JP7': 'Mitsubishi (For Plymouth trucks)',
            'JW6': 'Mitsubishi Fuso',
            'JN':  'Nissan',
            'JN1': 'Nissan / Infiniti (Car)',
            'JN3': 'Nissan (Incomplete vehicle)',
            'JN6': 'Nissan (Truck)',
            'JN8': 'Nissan / Infiniti (MPV/SUV)',
            'JNA': 'Nissan / UD Trucks (Incomplete vehicle)',
            'JNC': 'Nissan / UD Trucks',
            'JNE': 'Nissan / UD Trucks (Truck)',
            'JNK': 'Infiniti / Nissan (Car)',
            'JNR': 'Infiniti / Nissan (SUV)',
            'JNX': 'Infiniti / Nissan (Incomplete vehicle)',
            'JPC': 'Nissan / UD Trucks',
            'JF1': 'Subaru / Fuji Heavy Industries (Car)',
            'JF2': 'Subaru / Fuji Heavy Industries (SUV)',
            'JF3': 'Subaru / Fuji Heavy Industries (Truck)',
            'JF4': 'Subaru / Fuji Heavy Industries (For Saab 9-2X)',
            'JG1': 'Suzuki (For Chevrolet/Geo cars)',
            'JG7': 'Suzuki (For Pontiac/Asuna cars)',
            'JGC': 'Suzuki (For Chevrolet/Geo SUV)',
            'JGT': 'Suzuki (For GMC SUV)',
            'JS':  'Suzuki',
            'JS1': 'Suzuki (Motorcycle, incl. for Kawasaki)',
            'JS2': 'Suzuki (Car)',
            'JS3': 'Suzuki (SUV)',
            'JSA': 'Suzuki (For Kawasaki KFX400 ATV)',
            'JSK': 'Suzuki (For Kawasaki KLX125 motorcycle)',
            'JSL': 'Suzuki (For Kawasaki KFX400 ATV)',
            'JT':  'Toyota',
            'JT2': 'Toyota (Car)',
            'JT3': 'Toyota (MPV/SUV)',
            'JT4': 'Toyota (Truck)',
            'JT5': 'Toyota (Incomplete vehicle)',
            'JT6': 'Lexus / Toyota (SUV)',
            'JT8': 'Lexus / Toyota (Car)',
            'JTD': 'Toyota (Car)',
            'JTE': 'Toyota (MPV/SUV)',
            'JTF': 'Toyota (Van/Truck)',
            'JTG': 'Toyota (MPV/Bus)',
            'JTH': 'Lexus / Toyota (Car)',
            'JTJ': 'Lexus / Toyota (SUV)',
            'JTK': 'Toyota (Car)',
            'JTL': 'Toyota (SUV)',
            'JTM': 'Toyota (SUV)',
            'JTN': 'Toyota (Car)',
            'JY':  'Yamaha',
            'JY3': 'Yamaha (3-wheel ATV)', 
            'JY4': 'Yamaha (4-wheel ATV)',
            'JYA': 'Yamaha (Motorcycle)',
            'JYE': 'Yamaha (Snowmobile)',
        },

        // Israel
        'Israel': {
            'KF3': 'Merkavim (Israel)',
            'KF6': 'Automotive Industries, Ltd. (Israel)',
            'KF9': 'Tomcar (Israel)',
        },

        // Sri Lanka
        'Sri Lanka': {
            'KAA': 'RS Automotive (Sri Lanka)',
            'KAL': 'Lanka Ashok Leyland (Sri Lanka)',
            'KA1': 'KEWR Technologies (Sri Lanka)',
        },

        // South Korea
        'South Korea': {
            'KLA': 'Daewoo / GM Korea',
            'KLT': 'Tata Daewoo',
            'KLU': 'Tata Daewoo',
            'KL1': 'GM Daewoo / GM Korea / Chevrolet (car)',
            'KL2': 'Daewoo / GM Daewoo / Pontiac',
            'KL3': 'GM Daewoo / GM Korea / Holden',
            'KL4': 'GM Korea / Buick',
            'KL5': 'GM Daewoo / Suzuki',
            'KL6': 'GM Daewoo / GMC',
            'KL7': 'GM Daewoo / GM Korea / Chevrolet (MPV/SUV)',
            'KL8': 'GM Daewoo / GM Korea / Chevrolet (Spark)',
            'KMA': 'Asia Motors',
            'KME': 'Hyundai (commercial truck)',
            'KMF': 'Hyundai (van & commercial truck & Bering Truck)',
            'KMH': 'Hyundai (car)',
            'KMJ': 'Hyundai (bus & minibus)',
            'KMT': 'Genesis Motor (car)',
            'KMU': 'Genesis Motor (SUV)',
            'KMY': 'Daelim Motor Company / DNA Motors',
            'KM4': 'Hyosung Motors / S&T Motors / KR Motors',
            'KM8': 'Hyundai (SUV)',
            'KNA': 'Kia (car)',
            'KNC': 'Kia (car)',
            'KNE': 'Kia (car)',
            'KND': 'Kia (SUV/MPV) / Hyundai Entourage',
            'KNG': 'Kia (Granbird)',
            'KNJ': 'Ford (Festiva & Aspire)',
            'KNM': 'Renault Samsung Motors / Nissan (Rogue, made by Renault Samsung Motors)',
            'KPA': 'KG Mobility (pickup)',
            'KPB': 'KG Mobility (car)',
            'KM9': 'Edison Motors / KG Mobility (Commercial Buses)',
            'KPH': 'Mitsubishi (Precis)',
            'KPT': 'KG Mobility (SUV/MPV)',
        },

        // China
        'China': {
            'L1C': 'Hubei Huawei Special-Purpose Automobile',
            'L2C': 'Chery Jaguar Land Rover',
            'L5Y': 'Znen Taizhou Zhongneng Motorcycle Co. Ltd.',
            'L6T': 'Geely',
            'L8A': 'Jinhua Youngman Automobile Manufacturing Co., Ltd.',
            'L8Y': 'Zhejiang Jonway Motorcycle Manufacturing Co., Ltd.',
            'L9N': 'Zhejiang Taotao Vehicles Co., Ltd.',
            'LA6': 'King Long',
            'LA9': 'BYD Auto',
            'LC0': 'BYD Auto Industry Co. Ltd.',
            'LAL': 'Sundiro Honda Motorcycle Co., Ltd.',
            'LB1': 'Fujian Benz',
            'LB2': 'Geely (motorcycle)',
            'LB3': 'Geely',
            'LBB': 'Qianjiang Motorcycle & Benelli',
            'LBE': 'Beijing Hyundai / Hyundai Sonata Taxi (DT23)',
            'LBP': 'Chongqing Jianshe Yamaha Motor Co. Ltd.',
            'LBV': 'BMW Brilliance',
            'LC2': 'Changzhou Kwang Yang Motor Co., Ltd.',
            'LC6': 'Changzhou Haojue Suzuki Motorcycle Co. Ltd.',
            'LCE': 'CF Moto (Chunfeng Holding Group)',
            'LCR': 'Gonow',
            'LDC': 'Dongfeng Peugeot-Citroën',
            'LDK': 'FAW Bus (Dalian) Co., Ltd.',
            'LDN': 'Soueast',
            'LDY': 'Zhongtong Bus',
            'LE4': 'Beijing Benz / Daimler Chrysler Automotive',
            'LEF': 'JMC',
            'LET': 'Jiangxi Isuzu',
            'LF3': 'Lifan (motorcycle)',
            'LFB': 'FAW Jilin',
            'LFM': 'FAW Toyota',
            'LFN': 'FAW Bus (Wuxi) Co., Ltd.',
            'LFP': 'FAW Car',
            'LFV': 'FAW-Volkswagen',
            'LGA': 'Dongfeng Commercial Vehicle (trucks)',
            'LGB': 'Dongfeng Nissan',
            'LGC': 'Dongfeng Commercial Vehicle (buses)',
            'LGG': 'Dongfeng Liuzhou Motor',
            'LGJ': 'Dongfeng Fengshen (Aeolus)',
            'LGL': 'Guilin Daewoo',
            'LGW': 'Great Wall (Haval)',
            'LGX': 'BYD Auto',
            'LGZ': 'Guangzhou Denway Bus',
            'LH1': 'FAW Haima',
            'LHG': 'Guangzhou Honda',
            'LJ1': 'JAC',
            'LJ8': 'Zotye Auto',
            'LJC': 'Jincheng Corporation',
            'LJD': 'Dongfeng Yueda Kia',
            'LJN': 'Zhengzhou Nissan',
            'LJS': 'Yaxing Coach',
            'LJU': 'Shanghai Maple Automobile / Kandi',
            'LJV': 'Sinotruk Chengdu Wangpai Commercial Vehicle',
            'LJX': 'JMC Ford',
            'LKC': 'Changhe',
            'LKG': 'Youngman Lotus Automobile Co., Ltd.',
            'LKL': 'Higer Bus',
            'LKT': 'Yunnan Lifan Junma Vehicle Co. (commercial)',
            'LL3': 'Xiamen Golden Dragon Bus Co. Ltd.',
            'LL6': 'GAC Mitsubishi',
            'LL8': 'Jiangsu Linhai Yamaha Motor Co., Ltd.',
            'LLC': 'Loncin Holdings',
            'LLN': 'Qoros',
            'LLV': 'Lifan',
            'LM6': 'SWM (automobiles)',
            'LMG': 'GAC Trumpchi',
            'LNB': 'BAIC Motor',
            'LNP': 'NAC MG UK / Nanjing Fiat Automobile',
            'LNY': 'Yuejin',
            'LPA': 'Changan PSA (DS Automobiles)',
            'LPE': 'BYD Auto',
            'LPS': 'Polestar',
            'LRB': 'SAIC GM Buick',
            'LRD': 'Beijing Foton Daimler Automotive (Auman trucks)',
            'LRE': 'SAIC GM Cadillac',
            'LRW': 'Tesla (China)',
            'LS5': 'Changan Automobile / Changan Suzuki',
            'LS7': 'JMC Heavy Duty Vehicle',
            'LSF': 'SAIC Maxus / Shanghai Sunwin Bus',
            'LSG': 'SAIC GM Chevrolet',
            'LSH': 'SAIC Maxus',
            'LSJ': 'SAIC MG / SAIC Roewe',
            'LSK': 'SAIC Maxus',
            'LSV': 'SAIC Volkswagen',
            'LSY': 'Brilliance / Jinbei GM',
            'LTA': 'ZX Auto',
            'LTN': 'Soueast (Chrysler & Dodge)',
            'LTV': 'FAW Toyota (Tianjin)',
            'LUC': 'Honda Automobile (China)',
            'LUD': 'Dongfeng Nissan Diesel Motor Co. Ltd.',
            'LUX': 'Dongfeng Yulon Motor Co. Ltd.',
            'LVA': 'Foton Motor',
            'LVB': 'Foton Motor',
            'LVC': 'Foton Motor',
            'LVF': 'Changhe Suzuki',
            'LVG': 'GAC Toyota',
            'LVH': 'Dongfeng Honda',
            'LVM': 'Chery Commercial Vehicle',
            'LVR': 'Changan Mazda',
            'LVS': 'Changan Ford / Changan Ford Mazda',
            'LVV': 'Chery',
            'LVX': 'Landwind',
            'LVY': 'Volvo Cars (Daqing factory)',
            'LVZ': 'DFSK Motor',
            'LWB': 'Wuyang Honda Motorcycle (Guangzhou)',
            'LWL': 'Qingling Isuzu',
            'LWV': 'GAC Fiat Chrysler',
            'LXV': 'Beijing Borgward Automotive Co., Ltd.',
            'LXY': 'Chongqing Shineray Motorcycle Co., Ltd.',
            'LYB': 'Weichai Yaxing Automobile (Yangzhou)',
            'LYM': 'Zhuzhou Jianshe Yamaha Motorcycle Co., Ltd.',
            'LYV': 'Volvo Cars (Chengdu & Luqiao factories)',
            'LZF': 'SAIC Iveco Hongyan',
            'LZG': 'Shaanxi Automobile Group (Shacman Bus)',
            'LZK': 'Sinotruk (CNHTC) Huanghe Bus',
            'LZS': 'Zongshen',
            'LZU': 'Guangzhou Isuzu Bus',
            'LZW': 'SAIC GM Wuling',
            'LZY': 'Yutong',
            'LZZ': 'Sinotruk (CNHTC) Howo / Sitrak',
        },

        // India
        'India': {
            'MA1': 'Mahindra',
            'MA3': 'Maruti Suzuki India Limited',
            'MA6': 'General Motors India Pvt. Ltd.',
            'MA7': 'Hindustan Motors / Mitsubishi Motors (by Hindustan Motors) / Isuzu (by Hindustan Motors)',
            'MAH': 'Fiat India Automobiles Pvt. Ltd.',
            'MAJ': 'Ford India',
            'MAK': 'Honda Cars India',
            'MAL': 'Hyundai Motor India',
            'MAN': 'Eicher Polaris (Multix)',
            'MAT': 'Tata Motors',
            'MB1': 'Ashok Leyland Ltd.',
            'MB8': 'Suzuki Motorcycle India Limited',
            'MBF': 'Royal Enfield',
            'MBH': 'Nissan Pixo (by Maruti Suzuki India Limited)',
            'MBJ': 'Toyota Kirloskar Motor Pvt. Ltd.',
            'MBK': 'MAN Trucks India Pvt. Ltd.',
            'MBL': 'Hero MotoCorp',
            'MBU': 'Swaraj Vehicles Limited',
            'MBV': 'Premier Automobiles Limited',
            'MBX': 'Piaggio India (Piaggio Ape)',
            'MBY': 'Asia Motor Works Ltd.',
            'MC1': 'Force Motors Limited',
            'MC2': 'Eicher Motors Limited',
            'MC4': 'Dilip Chhabria Design Pvt. Ltd.',
            'MCA': 'FCA India Automobiles Pvt. Ltd.',
            'MCB': 'General Motors India Pvt. Ltd.',
            'MCD': 'Mahindra Two Wheelers',
            'MCG': 'Atul Auto',
            'MCL': 'International Cars And Motors Ltd.',
            'MD2': 'Bajaj Auto Ltd. (includes KTM and Husqvarna)',
            'MD6': 'TVS Motor Company',
            'MD7': 'LML Ltd. (includes Genuine Scooter Company Stella)',
            'MDE': 'Kinetic Engineering Limited',
            'MDH': 'Nissan Motor India Pvt. Ltd.',
            'MDT': 'Kerala Automobiles Limited',
            'ME1': 'India Yamaha Motor Pvt. Ltd.',
            'ME3': 'Royal Enfield',
            'ME4': 'Honda Motorcycle and Scooter India',
            'ME9': 'BUYMYEV Technology Pvt. Ltd.',
            'MEC': 'Daimler India Commercial Vehicles Pvt. Ltd. (BharatBenz)',
            'MEE': 'Renault India Private Limited',
            'MEG': 'Harley-Davidson India',
            'MER': 'Benelli',
            'MET': 'Piaggio India (Vespa)',
            'MEX': 'Škoda Auto Volkswagen India Pvt. Ltd. (2015–present)',
            'MYH': 'Ather Energy',
            'MZ7': 'MG Motor India Pvt. Ltd.',
            'MZB': 'Kia India Pvt. Ltd.',
            'MZD': 'Classic Legends Pvt. Ltd. (Jawa)',
            'M3G': 'Isuzu Motors India',
            'M6F': 'UM Lohia Two Wheelers Pvt. Ltd.',
        },

        // Indonesia
        'Indonesia': {
            'MH1': 'PT Astra Honda Motor',
            'MH3': 'PT Yamaha Indonesia Motor Mfg.',
            'MH4': 'PT Kawasaki Motor Indonesia',
            'MHF': 'PT Toyota Astra Motor',
            'MHH': 'BMW (cars, 2003–2019, local assembly attribution uncertain)',
            'MHK': 'PT Astra Daihatsu Motor (includes Toyotas made by Astra Daihatsu)',
            'MHL': 'PT Mercedes-Benz Indonesia',
            'MHR': 'PT Honda Prospect Motor',
            'MHY': 'PT Suzuki Indomobil Motor',
            'MJB': 'GM Indonesia',
            'MK2': 'Mitsubishi Motors Krama Yudha Indonesia',
            'MK3': 'PT SGMW Motor Indonesia (Wuling)',
        },

        // Thailand
        'Thailand': {
            'ML0': 'Ducati Motor (Thailand) Co., Ltd.',
            'ML3': 'Mitsubishi Motors (Thailand)',
            'ML5': 'Kawasaki Motors Enterprise Co. Ltd.',
            'MLC': 'Thai Suzuki Motor Co., Ltd.',
            'MLE': 'Thai Yamaha Motor Co., Ltd.',
            'MLH': 'Honda (motorcycle)',
            'MLY': 'Harley-Davidson (Thailand) Ltd.',
            'MM0': 'Mazda (Ford-Mazda AAT plant)',
            'MM6': 'Mazda (Ford-Mazda AAT plant)',
            'MM7': 'Mazda (Ford-Mazda AAT plant)',
            'MM8': 'Mazda (Ford-Mazda AAT plant)',
            'MMA': 'Mitsubishi Motors (Thailand)',
            'MMB': 'Mitsubishi Motors (Thailand)',
            'MMC': 'Mitsubishi Motors (Thailand)',
            'MMD': 'Mitsubishi Motors (Thailand)',
            'MMF': 'BMW',
            'MMH': 'Tata Motors (Thailand)',
            'MMK': 'Toyota (Toyota Auto Works plant)',
            'MMM': 'Chevrolet (Thailand)',
            'MML': 'MG (Thailand)',
            'MMR': 'Subaru (Thailand)',
            'MMS': 'Suzuki (Thailand)',
            'MMT': 'Mitsubishi Motors (Thailand)',
            'MMU': 'Holden (Thailand)',
            'MNA': 'Ford (Ford-Mazda AAT plant, export to Australia/New Zealand)',
            'MNB': 'Ford (Ford-Mazda AAT plant, export to RHD markets)',
            'MNC': 'Ford (Ford-Mazda AAT plant, export to LHD markets)',
            'MNK': 'Hino Motors Manufacturing (Thailand) Co. Ltd.',
            'MNT': 'Nissan Motor (Thailand)',
            'MPA': 'Isuzu Motors Company (Thailand)',
            'MPB': 'Ford (FTM plant)',
            'MP1': 'Isuzu Motors Company (Thailand)',
            'MP2': 'Mazda BT-50 (built by Isuzu Motors Thailand)',
            'MP5': 'Foton (Thailand)',
            'MRH': 'Honda (car, Thailand)',
            'MR0': 'Toyota (Ban Pho & Samrong plants)',
            'MR1': 'Toyota (Samrong plant, Fortuner)',
            'MR2': 'Toyota (Gateway plant)',
            'MRX': 'BYD Auto (Thailand) Co., Ltd.',
        },

        // Myanmar
        'Myanmar': {
            'MS0': 'SSS Motors Myanmar / Kia',
            'MS3': 'Suzuki Myanmar Motor Co., Ltd.',
        },

        // Kazakhstan
        'Kazakhstan': {
            'MXV': 'IMZ-Ural (Ural Motorcycles)',
            'MX3': 'Hyundai Trans Auto',
        },

        // Iran
        'Iran': {
            'N3C': 'Kavir Motor Company (Yektaz)',
            'N58': 'Kavir Motor Company (Eurasia)',
            'NAA': 'Iran Khodro Company',
            'NAD': 'Saipa Diesel',
            'NAG': 'Bahman Industrial Group',
            'NAP': 'Pars Khodro',
            'NAS': 'Saipa Co.',
            'NC0': 'Oghab Afshan (bus)',
        },

        // Pakistan
        'Pakistan': {
            'NFB': 'Honda Atlas Cars Pakistan Ltd.',
            'NG3': 'Lucky Motor Corporation',
        },

        // Turkey
        'Turkey': {
            'NLA': 'Honda (cars)',
            'NLC': 'Askam Kamyon Imalat Ve Ticaret A.S.',
            'NLH': 'Hyundai Assan Otomotiv (car/SUV)',
            'NLJ': 'Hyundai Assan Otomotiv (van)',
            'NLN': 'Karsan Automotive Industry & Trade',
            'NLR': 'Otokar',
            'NLT': 'TEMSA',
            'NL1': 'Togg',
            'NMA': 'MAN Türkiye A.Ş.',
            'NMB': 'Mercedes-Benz Türk A.S.',
            'NMC': 'BMC Otomotiv Sanayi ve Ticaret A.Ş.',
            'NMH': 'Honda (motorcycle)',
            'NMT': 'Toyota Motor Manufacturing Turkey',
            'NM0': 'Ford Otosan',
            'NM1': 'Oyak-Renault Oto Fab AS',
            'NM4': 'Tofas (Türk Otomobil Fabrikası AS)',
            'NNA': 'Anadolu Isuzu',
        },

        // Philippines
        'Philippines': {
            'PAB': 'Isuzu Philippines Corporation',
            'PAD': 'Honda Cars Philippines',
            'PAF': 'BMW Philippines',
            'PE1': 'Ford Motor Company Philippines',
            'PE3': 'Mazda Philippines (made by Ford Motor Company Philippines)',
        },

        // Malaysia
        'Malaysia': {
            'PL1': 'Proton',
            'PL8': 'Hyundai / Inokom',
            'PLP': 'Subaru',
            'PLZ': 'Isuzu Malaysia',
            'PMH': 'Honda (car)',
            'PML': 'Hicom',
            'PM1': 'BMW',
            'PM2': 'Perodua',
            'PM9': 'Bufori',
            'PMK': 'Honda Boon Siew (motorcycle)',
            'PMN': 'Modenas',
            'PMV': 'Hong Leong Yamaha Motor Sdn. Bhd.',
            'PNA': 'Naza / Kia / Peugeot',
            'PNV': 'Volvo Cars',
            'PN1': 'Toyota',
            'PN2': 'Toyota',
            'PN8': 'Nissan',
            'PP1': 'Mazda',
            'PP3': 'Hyundai',
            'PPP': 'Suzuki',
            'PPV': 'Volkswagen',
            'PR8': 'Ford',
            'PRA': 'Sinotruk',
            'PRB': 'Jaecoo (Chery Jaecoo)',
            'PRH': 'Chery',
            'PRN': 'GAC Trumpchi (made by Warisan Tan Chong Automotif Malaysia)',
        },

        // Taiwan
        'Taiwan': {
            'LFA': 'Ford Lio Ho Motor Co. Ltd. (old designation)',
            'LM1': 'Tai Ling Motor Co. Ltd. (old designation)',
            'LM4': 'Tai Ling Motor Co. Ltd. (old designation)',
            'LPR': 'Yamaha Motor Taiwan Co. Ltd. (old designation)',
            'RF3': 'Aeon Motor',
            'RF5': 'Yulon Motor Co. Ltd.',
            'RFB': 'Kymco',
            'RFC': 'Taiwan Golden Bee',
            'RFD': 'Tai Ling Motor Co. Ltd. (new designation)',
            'RFG': 'SYM Motors',
            'RFV': 'PGO Scooters (includes Genuine Scooter Company models)',
            'RGS': 'Kawasaki (made by Kymco)',
            'RHA': 'Ford Lio Ho Motor Co. Ltd. (new designation)',
            'RK7': 'Kawasaki ATV (made by Tai Ling Motor Co. Ltd., rebadged Suzuki ATV, new designation)',
            'RKJ': 'Prince Motors Taiwan',
            'RKL': 'Kuozui Motors (Toyota)',
            'RKM': 'China Motor Corporation',
            'RKR': 'Yamaha Motor Taiwan Co. Ltd. (new designation)',
            'RKT': 'Honda Taiwan',
        },

        // Vietnam
        'Vietnam': {
            'RL0': 'Ford Vietnam',
            'RL4': 'Toyota Motor Vietnam',
            'RLA': 'Vina Star Motors Corp. – Mitsubishi',
            'RLC': 'Yamaha Motor Vietnam Co. Ltd.',
            'RLE': 'Isuzu Vietnam Co.',
            'RLF': 'BMW (cars, 2003–2014, Vietnam)',
            'RLH': 'Honda Vietnam Co. Ltd.',
            'RLL': 'VinFast (SUV)',
            'RLM': 'Mercedes-Benz Vietnam',
            'RLV': 'Vietnam Precision Industrial Co. Ltd. (Can-Am DS 70 & DS 90)',
            'RP8': 'Piaggio Vietnam Co. Ltd.',
        },

        // Hong Kong
        'Hong Kong': {
            'R4N': 'Elyx Smart Technology Holdings (Hong Kong) Ltd.',
        },
    },
    /**
     * Europe
     */

    Europe: {
        // United Kingdom
        'United Kingdom': {
            'SA9': 'Morgan Motor Company (<500 units)',
            'SA9_OX': 'OX Global (<500 units)',
            'SA9_005': 'Panther (<500 units)',
            'SA9_019': 'TVR (<500 units)',
            'SA9_039': 'Westfield Sportscars (<500 units)',
            'SA9_048': 'McLaren F1 (<500 units)',
            'SA9_050': 'Marcos Engineering (<500 units)',
            'SA9_130': 'MG Sport and Racing (<500 units)',
            'SA9_202': 'Morgan 3-Wheeler (<500 units)',
            'SA9_506': 'KaiserRushforth (<500 units)', 
            'SA9_AC': 'AC Car Group Ltd (<500 units).', 
        },

        // United Kingdom
        'United Kingdom': {
            'SAA': 'Austin',
            'SAB': 'Optare',
            'SAD': 'Daimler (until April 1987) / Jaguar SUV',
            'SAF': 'ERF',
            'SAH': 'Honda (made by Austin Rover Group)',
            'SAJ': 'Jaguar',
            'SAL': 'Land Rover',
            'SAM': 'Morris',
            'SAR': 'Rover & MG Rover Group',
            'SAT': 'Triumph (car)',
            'SAX': 'Austin Rover Group (including Sterling Cars)',
            'SAY': 'Norton Motorcycles',
            'SAZ': 'Freight Rover',
            'SBB': 'Leyland Vehicles',
            'SBC': 'Iveco Ford Truck',
            'SBJ': 'Leyland Bus',
            'SBL': 'Leyland Motors & Leyland DAF',
            'SBM': 'McLaren Group',
            'SBS': 'Scammell',
            'SBV': 'Kenworth & Peterbilt trucks (made by Leyland Trucks)',
            'SB1': 'Toyota Manufacturing UK',
            'SCA': 'Rolls-Royce Motor Cars & Rolls-Royce Motors (car)',
            'SCB': 'Bentley Motors Limited',
            'SCC': 'Lotus Cars Limited',
            'SCE': 'DeLorean',
            'SCF': 'Aston Martin Lagonda Limited',
            'SCG': 'Triumph Engineering (original Triumph Motorcycle company)',
            'SCK': 'Ifor Williams Trailers',
            'SCR': 'London Electric Vehicle Company / London Taxi Company / London Taxis International',
            'SCV': 'Volvo Truck & Bus',
            'SC6': 'INEOS Automotive',
            'SDB': 'Talbot Motor Company',
            'SDF': 'Dodge Trucks (UK, 1981–1984)',
            'SDG': 'Renault Trucks Industries (1985–1992)',
            'SDK': 'Caterham Cars',
            'SDL': 'TVR',
            'SDP': 'MG Motor NAC MG UK & MG Motor UK',
            'SD7': 'Aston Martin SUVs',
            'SED': 'IBC Vehicles (Isuzu Bedford Company)',
            'SEG': 'Dennis Eagle',
            'SEY': 'LDV Group',
            'SFA': 'Ford of Britain',
            'SFD': 'Dennis',
            'SFE': 'Alexander Dennis',
            'SFN': 'Foden',
            'SFZ': 'Tesla Roadster (made by Lotus)',
            'SGD': 'Swift Group Ltd.',
            'SHH': 'Honda UK Manufacturing (car)',
            'SHS': 'Honda UK Manufacturing (SUV)',
            'SJA': 'Bentley (SUV)',
            'SJK': 'Nissan Motor Manufacturing UK (Infiniti)',
            'SJN': 'Nissan Motor Manufacturing UK (Nissan)',
            'SKA': 'Vauxhall Motors',
            'SKF': 'Bedford Vehicles',
            'SLA': 'Rolls-Royce Motor Cars (SUV)',
            'SLP': 'JC Bamford Excavators',
            'SLV': 'Volvo Bus',
            'SMT': 'Triumph Motorcycles Ltd (current Triumph Motorcycle company)',
        },

        // East Germany
        'East Germany': {
            'SNE': 'Wartburg',
            'SNT': 'Trabant',
            'SNZ': 'MZ Motorrad- und Zweiradwerk',
        },

        // Poland
        'Poland': {
            'SUA': 'Sanocka Fabryka Autobusow Sfa / Autosan',
            'SUD': 'Wielton',
            'SUE': 'BOSMAL',
            'SUF': 'Fabryka Samochodów Małolitrażowych',
            'SUJ': 'Jelcz',
            'SUL': 'FSC Lublin Automotive Factory',
            'SUM': 'Metal-Fach Sp. z o.o.',
            'SUN': 'FSD',
            'SUP': 'Fabryka Samochodow Osobowych',
            'SUR': 'Factory of Agricultural Vehicles “Polmo” in Poznań',
            'SUS': 'Fabryka Samochodów Ciężarowych “Star”',
            'SUU': 'Solaris Bus & Coach',
            'SUZ': 'Zasław',
            'SVS': 'BODEX',
            'SW9': 'Solbus',
            'SX9': 'SOMMER',
            'SZ9': 'EPOKA',
            'SZA': 'Scania Production Slupsk',
            'SZB': 'Pronar',
            'SZH': 'BWW',
            'SZR': 'Niewiadów (trailers)',
        },

        // Switzerland
        'Switzerland': {
            'TAM': 'Mowag',
            'TAP': 'Polaris Europe (based in Switzerland)',
            'TAW': 'Nutzfahrzeuggesellschaft Arbon & Wetzikon (NAW, former Swiss manufacturer of commercial vehicles, until 2003)',
            'TCC': 'Micro Compact Car (until 5/99)',
            'TEB': 'Bucher Municipal (including Johnston Sweepers of the UK, owned by Bucher Municipal of Switzerland)',
            'TH9': 'Carrosserie HESS AG (Swiss manufacturer of buses and trolleybuses)',
        },

        // Czech Republic
        'Czech Republic': {
            'TK9': 'SOR Libchavy',
            'TLJ': 'Jawa Moto',
            'TMA': 'Hyundai Motor Manufacturing Czech (car)',
            'TMB': 'Škoda Auto AS',
            'TMC': 'Hyundai Motor Manufacturing Czech (SUV)',
            'TMK': 'Karosa',
            'TMP': 'Škoda Ostrov',
            'TMT': 'Tatra (car)',
            'TNA': 'Avia / Daewoo Avia',
            'TNT': 'Tatra (trucks)',
            'TNU': 'Tatra (trucks)',
        },

        // Hungary
        'Hungary': {
            'TRA': 'Ikarus Bus',
            'TRU': 'Audi',
            'TSM': 'Suzuki',
        },

        // Portugal
        'Portugal': {
            'TW1': 'Toyota Caetano Portugal',
            'TW3': 'Renault Portuguesa SARL',
            'TW7': 'Mini Moke (made by British Leyland & Austin Rover)',
            'TW8': 'General Motors De Portugal Lda',
            'TWG': 'Salvador Caetano',
            'TX5': 'Mini Moke (made by Cagiva)',
            'TYA': 'Mitsubishi Fuso Truck and Bus Corp.',
            'TYB': 'Mitsubishi Fuso Truck and Bus Corp.',
        },

        // Slovenia
        'Slovenia': {
            'U5Y': 'Kia Motors Slovakia (car)',
            'U6Y': 'Kia Motors Slovakia (SUV)',
        },

        // Denmark
        'Denmark': {
            'UKH': 'HARDI International A/S (Agricultural Machinery)',
            'ULA': 'ASA-LIFT: Vegetable Technology Specialist (Agricultural Machinery)',
        },

        // Romania
        'Romania': {
            'UU1': 'Dacia',
            'UU2': 'Oltcit',
            'UU3': 'ARO',
            'UU5': 'Rocar',
            'UU6': 'Daewoo Romania',
            'UU7': 'Euro Bus Diamond',
            'UU9': 'Astra Bus',
            'UZT': 'UTB (Uzina de Tractoare Brașov)',
        },

        // Austria
        'Austria': {
            'VA0': 'ÖAF',
            'VAG': 'Steyr-Daimler-Puch (Puch G & Steyr-Puch Pinzgauer)',
            'VAN': 'Steyr-Daimler-Puch (Steyr Trucks)',
            'VAK': 'Kässbohrer Transport Technik',
            'VBK': 'KTM / Husqvarna Motorcycles & Gas Gas (under KTM ownership)',
            'VCF': 'Fisker Inc. (Fisker Ocean, made by Magna Steyr)',
        },

        // France
        'France': {
            'VF1': 'Renault & Eagle Medallion (made by Renault)',
            'VF2': 'Renault Trucks',
            'VF3': 'Peugeot',
            'VF4': 'Talbot',
            'VF5': 'Iveco Unic',
            'VF6': 'Renault Trucks',
            'VF7': 'Citroën',
            'VF8': 'Matra / Talbot / Simca',
            'VF9_607': '607 Mathieu Fayat Group',
            'VF9_673': 'Venturi Automobiles',
            'VF9_795': 'Bugatti Automobiles S.A.S.',
            'VFA': 'Alpine',
            'VG5': 'MBK & Yamaha Motor',
            'VG6': 'Renault Trucks & Mack Trucks (medium duty trucks, made by Renault Trucks)',
            'VG7': 'Renault Trucks',
            'VG8': 'Renault Trucks',
            'VG9': 'EVRARD (Agricultural Machinery)',
            'VGA': 'Peugeot Motocycles',
            'VJ1': 'Heuliez Bus',
            'VK8': 'Venturi Automobiles',
            'VL4': 'Bluecar',
            'VLU': 'Scania Production Angers',
            'VMK': 'Renault Sport Spider',
            'VN1': 'Renault SOVAB',
            'VNE': 'Iveco Bus',
            'VNK': 'Toyota Motor Manufacturing France',
            'VNV': 'Nissan',
            'VR1': 'DS Automobiles',
            'VR3': 'Peugeot',
            'VR7': 'Citroën',
            'VPS': 'MLT Automotive',
            'VXE': 'Opel Automobile GmbH / Vauxhall (van)',
            'VXK': 'Opel Automobile GmbH / Vauxhall (car/SUV)',
            'VYC': 'Lancia (models on PSA CMP platform)',
        },

        // Spain
        'Spain': {
            'VS1': 'Pegaso',
            'VS5': 'Renault España',
            'VF1': 'Renault Samsung QM3',
            'VS6': 'Ford España',
            'VS7': 'Citroën',
            'VS8': 'Peugeot',
            'VS9': 'Comarth',
            'VSC': 'Mercedes-Benz España SA (Vitoria)',
            'VSE': 'Santana Motor',
            'VSK': 'Nissan Motor Iberica SA (passenger car / MPV / van / SUV / pickup & Ford Maverick 1993–1999)',
            'VSS': 'SEAT',
            'VSX': 'Opel Automobile España, SA',
            'VTD': 'Montesa Honda (Honda Montesa motorcycle models)',
            'VTH': 'Derbi',
            'VTL': 'Yamaha Motor España SA & Yamaha Sociedad Española de Motocicletas',
            'VTM': 'Montesa Honda (Honda motorcycle models)',
            'VTR': 'Gas Gas',
            'VTT': 'Suzuki Motor España (Motorcycle)',
            'VV9': 'Tauro Sport Auto',
            'VWA': 'Nissan Motor Ibérica S.A.',
        },

        // Serbia
        'Serbia': {
            'VX1': 'Zastava Automobiles',
        },

        // Croatia
        'Croatia': {
            'V31': 'Tvornica Autobusa Zagreb (TAZ)',
            'V39_AB8': 'Rimac Automobili',
        },

        // Germany
        'Germany': {
            'WAC': 'Audi / Porsche RS 2 Avant',
            'WAG': 'Neoplan',
            'WAU': 'Audi (car)',
            'WAP': 'Alpina',
            'WUA': 'Audi (SUV)',
            'WBA': 'BMW (car)',
            'WBS': 'BMW M (car)',
            'WBX': 'BMW (SUV)',
            'WBY': 'BMW i (car)',
            'WB1': 'BMW Motorrad (Motorcycle)',
            'WB3': 'BMW Motorrad (Motorcycles made in India)',
            'WB4': 'BMW Motorrad (Motorscooters made in China)',
            'WB5': 'BMW i (SUV)',
            'WB6': 'BMW M (SUV)',
            'WCD': 'Freightliner Sprinter "bus" (van with more than 3 rows of seats) 2008–2019',
            'WD0': 'Dodge Sprinter truck (cargo van with 1 row of seats) 2005–2009',
            'WD1': 'Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 incomplete vehicle',
            'WD2': 'Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 truck (cargo van with 1 row of seats)',
            'WD3': 'Mercedes-Benz truck (cargo van with 1 row of seats) (North America)',
            'WD4': 'Mercedes-Benz MPV (van with 2 or 3 rows of seats) (North America)',
            'WD5': 'Freightliner Sprinter 2002 & Sprinter (Dodge or Freightliner) 2003–2005 MPV (van with 2 or 3 rows of seats)',
            'WD6': 'Freightliner Unimog (truck)',
            'WD7': 'Freightliner Unimog incomplete vehicle',
            'WD8': 'Dodge Sprinter MPV (van with 2 or 3 rows of seats) 2005–2009',
            'WDA': 'Mercedes-Benz incomplete vehicle (North America)',
            'WDB': 'Mercedes-Benz & Maybach',
            'WDC': 'Mercedes-Benz (SUV)',
            'WDD': 'Mercedes-Benz (car)',
            'WDF': 'Mercedes-Benz van (French & Spanish built models – Citan, Vito & X-Class)',
            'WDP': 'Freightliner Sprinter incomplete vehicle 2005–2019',
            'WDR': 'Freightliner Sprinter MPV (van with 2 or 3 rows of seats) 2005–2019',
            'WDW': 'Dodge Sprinter "bus" (van with more than 3 rows of seats) 2008–2009',
            'WDX': 'Dodge Sprinter incomplete vehicle 2005–2009',
            'WDY': 'Freightliner Sprinter truck (cargo van with 1 row of seats) 2005–2019',
            'WDZ': 'Mercedes-Benz "bus" (van with more than 3 rows of seats) (North America)',
            'WEB': 'EvoBus Mercedes-Benz buses',
            'WEL': 'e.GO Mobile AG',
            'WF0': 'Ford of Europe',
            'WF1': 'Merkur',
            'WJM': 'Iveco / Iveco Magirus',
            'WJR': 'Irmscher',
            'WKK': 'Setra & Karl Kässbohrer Fahrzeugwerke',
            'WKE': 'Krone Trailer',
            'WMA': 'MAN',
            'WME': 'Smart (from 5/99)',
            'WMW': 'Mini (car)',
            'WMX': 'Mercedes-AMG (used for Mercedes-Benz SLS AMG & Mercedes-AMG GT, not used in North America)',
            'WMZ': 'Mini (SUV)',
            'WNA': 'Next.e.GO Mobile SE',
            'WP0': 'Porsche (car)',
            'WP1': 'Porsche (SUV)',
            'WS5': 'StreetScooter',
            'WSM': 'Schmitz Cargobull',
            'WU1': 'Audi Sport GmbH (SUV)',
            'WVG': 'Volkswagen (SUV)',
            'WVM': 'Arbeitsgemeinschaft VW-MAN',
            'WVP': 'Viseon Bus',
            'WVW': 'Volkswagen (car)',
            'WV1': 'Volkswagen Commercial Vehicles',
            'WV2': 'Volkswagen Commercial Vehicles',
            'WZ1': 'Toyota Supra (Fifth generation)',
            'W04': 'Buick Regal & Buick Cascada',
            'W06': 'Cadillac Catera',
            'W08': 'Saturn Astra',
            'W09_B09': 'Bitter Cars',
            'W09_B16': 'Brabus',
            'W09_D05': 'Drögmöller',
            'W09_HA8': 'HWA AG',
            'W09_R06': 'Ruf Automobile',
            'W0L': 'Adam Opel AG / Vauxhall & Holden',
            'W0S': 'Opel Special Vehicles',
            'W0V': 'Opel Automobile GmbH / Vauxhall & Holden',
            'W1A': 'Smart',
            'W1H': 'Freightliner Econic',
            'W1K': 'Mercedes-Benz (car)',
            'W1N': 'Mercedes-Benz (SUV)',
            'W1T': 'Mercedes-Benz (truck)',
            'W1V': 'Mercedes-Benz (van)',
            'W1W': 'Mercedes-Benz MPV (van with 2 or 3 rows of seats) (North America)',
            'W1X': 'Mercedes-Benz incomplete vehicle (North America)',
            'W1Y': 'Mercedes-Benz truck (cargo van with 1 row of seats) (North America)',
            'W1Z': 'Mercedes-Benz "bus" (van with more than 3 rows of seats) (North America)',
            'W2W': 'Freightliner Sprinter MPV (van with 2 or 3 rows of seats)',
            'W2X': 'Freightliner Sprinter incomplete vehicle',
            'W2Y': 'Freightliner Sprinter truck (cargo van with 1 row of seats)',
            'W2Z': 'Freightliner Sprinter "bus" (van with more than 3 rows of seats)',
        },

        // Bulgaria
        'Bulgaria': {
            'XBB': 'Great Wall Motors/Litex Motors AD',
        },

        // Netherlands
        'Netherlands': {
            'XL9_003': 'Autobusfabriek Bova BV',
            'XL9_320': 'VDL Bova',
            'XL9_363': 'Spyker Cars',
            'XL9_A27': 'Groenewold Carrosseriefabriek B.V.',
            'XLB': 'Volvo Car B.V. / NedCar B.V. (Volvo Cars)',
            'XLE': 'Scania Nederland B.V.',
            'XLR': 'DAF Trucks & Leyland DAF',
            'XLV': 'DAF Bus',
            'XMC': 'NedCar B.V. Mitsubishi Motors',
            'XMG': 'VDL Bus International',
            'XNC': 'NedCar B.V. Mitsubishi Motors (Colt CZC convertible)',
            'XNL': 'VDL Bus & Coach',
            'XNT': 'Pacton Trailer',
            'XP7': 'Tesla Europe (based in the Netherlands)',
        },

        // Russia
        'Russia': {
            'XTA': 'AvtoVAZ',
            'XTB': 'AZLK',
            'XTC': 'KAMAZ',
            'XTE': 'ZAZ',
            'XTF': 'GolAZ',
            'XTH': 'GAZ',
            'XTT': 'UAZ',
            'XTY': 'LiAZ',
            'XU1': 'UAZ Special Purpose Vehicles',
            'XUF': 'General Motors Russia',
            'XUU': 'Chevrolet made by Avtotor',
            'XW7': 'Toyota Motor Manufacturing Russia',
            'XW8': 'Volkswagen Group Rus',
            'XWE': 'Hyundai Motor Company & Kia made by Avtotor',
            'X1E': 'KAvZ',
            'X1M': 'PAZ',
            'X4X': 'BMW made by Avtotor',
            'X7L': 'Renault Russia',
            'X8J': 'IMZ-Ural Ural Motorcycles',
            'X96': 'GAZ',
            'X9F': 'Ford Motor Company ZAO',
            'X9L': 'GM-AvtoVAZ',
            'X9P': 'Volvo Vostok ZAO Volvo Trucks',
            'X9X': 'Great Wall Motors IMS Avtotrade-12 LLC',
            'Z6F': 'Ford Sollers',
            'Z8N': 'Nissan Manufacturing Rus',
            'Z8T': 'PCMA Rus',
            'Z94': 'Hyundai Motor Manufacturing Rus',
            'Z9M': 'Mercedes-Benz Trucks Vostok',
        },

        // Uzbekistan
        'Uzbekistan': {
            'XWB': 'UzDaewoo GM Uzbekistan Ravon',
        },

        // Belarus
        'Belarus': {
            'Y4K': 'BelGee (Geely)',
        },

        // Ukraine
        'Ukraine': {
            'Y6D': 'ZAZ',
            'Y6J': 'Bogdan group',
            'Y6U': 'Škoda Auto made by Eurocar',
            'Y7B': 'Bogdan group',
            'Y7C': 'Great Wall Motors KrASZ',
        },

        // Belgium
        'Belgium': {
            'YAR': 'Toyota Motor Europe (based in Belgium) used for Toyota ProAce & Toyota ProAce City',
            'YB3': 'Volvo Trucks',
            'YB6': 'Jonckheere',
            'YC1': 'Honda',
            'YE2': 'Van Hool',
        },

        // Finland
        'Finland': {
            'YH2': 'Lynx (snowmobile)',
            'YH4': 'Fisker Automotive (Fisker Karma) built by Valmet Automotive',
            'YK1': 'Saab built by Valmet Automotive',
            'YK7': 'Sisu Auto',
        },

        // Sweden
        'Sweden': {
            'YS2': 'Scania, Södertälje truck',
            'YS3': 'Saab',
            'YS4': 'Scania, Katrineholm bus',
            'YSC': 'Cadillac BLS built by Saab',
            'YSM': 'Polestar',
            'YT9': 'Gin 1 Cars',
            'YT9_007': 'Koenigsegg Automotive AB',
            'YTN': 'Saab NEVS',
            'YU7': 'Husaberg Swedish built models',
            'YV1': 'Volvo Cars car',
            'YV2': 'Volvo Trucks',
            'YV3': 'Volvo Buses',
            'YV4': 'Volvo Cars SUV',
            'YV5': 'Volvo Trucks incomplete vehicle',
        },

        // Norway
        'Norway': {
            'YYC': 'Think Nordic',
        },

        // Italy
        'Italy': {
            'ZA9_A12': 'Lamborghini through mid 2003',
            'ZA9_D38': 'Cizeta Automobili SRL',
            'ZA9_D39': 'Bugatti Automobili S.p.A',
            'ZA9_F76': 'Pagani Automobili S.p.A',
            'ZA9_M09': 'Italdesign Automobili Speciali',
            'ZA9_M27': 'Dallara Stradale',
            'ZA9_M91': 'Automobili Pininfarina',
            'ZAA': 'Autobianchi',
            'ZAC': 'Jeep and Dodge Hornet',
            'ZAH': 'Rolfo',
            'ZAM': 'Maserati car',
            'ZAP': 'Piaggio and Vespa and Gilera',
            'ZAR': 'Alfa Romeo car & Nissan Cherry Europe',
            'ZAS': 'Alfa Romeo Alfasud & Sprint through 1989',
            'ZAS': 'Alfa Romeo SUV 2018-',
            'ZBA': 'BMW For South Africa',
            'ZBB': 'Gruppo Bertone',
            'ZBI': 'BMW For Indonesia',
            'ZBM': 'BMW For Philippines',
            'ZBN': 'Benelli',
            'ZBP': 'BMW For Malaysia',
            'ZBT': 'BMW For Thailand',
            'ZBW': 'Rayton-Fissore Magnum',
            'ZC2': 'Chrysler TC by Maserati',
            'ZC6': 'Effedi Veicoli Commerciali',
            'ZCF': 'Iveco',
            'ZCG': 'Cagiva & MV Agusta',
            'ZCG': 'Husqvarna Motorcycles Under MV Agusta ownership',
            'ZD0': 'Yamaha Motor Italia SpA & Belgarda SpA',
            'ZD3': 'Betamotor S.p.A.',
            'ZD4': 'Aprilia',
            'ZDC': 'Honda Italia Industriale S.p.A.',
            'ZDM': 'Ducati Motor Holding',
            'ZDT': 'De Tomaso Modena SpA',
            'ZDY': 'Cacciamali',
            'ZE8': 'Bremach',
            'ZES': 'Bimota',
            'ZF4': 'Qvale',
            'ZFA': 'Fiat car Also Fiat Fullback',
            'ZFB': 'Fiat MPV/SUV',
            'ZFC': 'Ram 1200',
            'ZFF': 'Ferrari',
            'ZFM': 'Fantic Motor',
            'ZFR': 'Pininfarina',
            'ZGA': 'Iveco Bus',
            'ZGU': 'Moto Guzzi',
            'ZHU': 'Husqvarna Motorcycles Under Cagiva ownership',
            'ZHW': 'Lamborghini car from mid 2003',
            'ZJM': 'Malaguti',
            'ZJN': 'Innocenti',
            'ZJT': 'Italjet',
            'ZKH': 'Husqvarna Motorcycles Srl Under BMW ownership',
            'ZK5': 'Hyundai Automobili Italia Importazioni',
            'ZLA': 'Lancia',
            'ZLM': 'Moto Morini srl',
            'ZLV': 'Laverda',
            'ZN0': 'SWM Motorcycles S.r.l.',
            'ZN3': 'Iveco Defence',
            'ZN6': 'Maserati SUV',
            'ZNN': 'Energica Motor Company',
            'ZPB': 'Lamborghini SUV',
            'ZPY': 'DR Automobiles',
        },

        // Slovenia
        'Slovenia': {
            'ZZ1': 'Tomos motorcycle',
        },
    },

    /**
     * North America
     */
    NorthAmerica: {
        // United States
        'United States': {
            '1A4': 'Chrysler brand MPV/SUV 2006–2009 only',
            '1A8': 'Chrysler brand MPV/SUV 2006–2009 only',
            '1AC': 'American Motors Corporation MPV',
            '1AF': 'American LaFrance truck',
            '1AM': 'American Motors Corporation car & Renault Alliance 1983 only',
            '1B3': 'Dodge car 1981–2011',
            '1B4': 'Dodge MPV/SUV 1981–2002',
            '1B6': 'Dodge incomplete vehicle 1981–2002',
            '1B7': 'Dodge truck 1981–2002',
            '1B9_133': 'Buell Motorcycle Company through mid 1995',
            '1B9_975': 'Motus Motorcycles',
            '1BA': 'Blue Bird Corporation bus',
            '1BB': 'Blue Bird Wanderlodge MPV',
            '1BD': 'Blue Bird Corporation incomplete vehicle',
            '1BL': 'Balko, Inc. from Ladysmith, WI',
            '1C3': 'Chrysler brand car 1981–2011',
            '1C3': 'Chrysler Group (all brands) car (including Lancia) 2012–',
            '1C4': 'Chrysler brand MPV 1990–2005',
            '1C4': 'Chrysler Group (all brands) MPV 2012–',
            '1C6': 'Chrysler Group (all brands) truck 2012–',
            '1C8': 'Chrysler brand MPV 2001–2005',
            '1C9_291': 'CX Automotive',
            '1CM': 'Checker Motors Corporation',
            '1CU': 'Cushman Haulster (Cushman division of Outboard Marine Corporation)',
            '1CY': 'Crane Carrier Company',
            '1D3': 'Dodge truck 2002–2009',
            '1D4': 'Dodge MPV/SUV 2003–2011 only',
            '1D7': 'Dodge truck 2002–2011',
            '1D8': 'Dodge MPV/SUV 2003–2009 only',
            '1F': 'Ford',
            '1F1': 'Ford SUV – limousine (through 2009)',
            '1F6': 'Ford stripped chassis made by Detroit Chassis LLC',
            '1F9_ST2': 'Seagrave',
            '1FA': 'Ford car',
            '1FB': 'Ford "bus" (van with more than 3 rows of seats)',
            '1FC': 'Ford stripped chassis made by Ford',
            '1FD': 'Ford incomplete vehicle (chassis cab)',
            '1FM': 'Ford MPV/SUV',
            '1FT': 'Ford truck',
            '1FU': 'Freightliner Trucks',
            '1FV': 'Freightliner Trucks',
            '1G': 'General Motors',
            '1G0': 'GMC "bus" (van with more than 3 rows of seats) 1981–1986 / Opel car 2007–2017',
            '1G1': 'Chevrolet car',
            '1G2': 'Pontiac car',
            '1G3': 'Oldsmobile car',
            '1G4': 'Buick car',
            '1G5': 'GMC MPV/SUV 1981–1986',
            '1G6': 'Cadillac car',
            '1G7': 'Pontiac car only sold by GM Canada',
            '1G8': 'Saturn car 1991–2010 / Chevrolet MPV/SUV 1981–1986',
            '1G9_495': 'Google & Waymo',
            '1GA': 'Chevrolet "bus" (van with more than 3 rows of seats)',
            '1GB': 'Chevrolet incomplete vehicles',
            '1GC': 'Chevrolet truck',
            '1GD': 'GMC incomplete vehicles',
            '1GE': 'Cadillac incomplete vehicle',
            '1GF': 'Flxible bus',
            '1GG': 'Isuzu pickup trucks made by GM',
            '1GH': 'Oldsmobile MPV/SUV 1990–2004 / Holden Acadia 2019–2020',
            '1GJ': 'GMC "bus" (van with more than 3 rows of seats) 1987–',
            '1GK': 'GMC MPV/SUV 1987–',
            '1GM': 'Pontiac MPV',
            '1GN': 'Chevrolet MPV/SUV 1987–',
            '1GT': 'GMC truck',
            '1GY': 'Cadillac SUV',
            '1H9_A': 'Crane Carrier Company',
            '1HA': 'Chevrolet incomplete vehicles made by Navistar International',
            '1HD': 'Harley-Davidson',
            '1HF': 'Honda motorcycle/ATV/UTV',
            '1HG': 'Honda car made by Honda of America Mfg. in Ohio',
            '1HS': 'International Trucks & Caterpillar Trucks truck',
            '1HT': 'International Trucks & Caterpillar Trucks & Chevrolet Silverado 4500HD–6500HD incomplete vehicle',
            '1HV': 'IC Bus incomplete bus',
            '1J4': 'Jeep SUV 1989–2011 (Chrysler-style VIN)',
            '1J7': 'Jeep truck 1989–1992 (Chrysler-style VIN)',
            '1J8': 'Jeep SUV 2002–2011 (Chrysler-style VIN)',
            '1JC': 'Jeep SUV 1981–1988 (AMC-style VIN)',
            '1JT': 'Jeep truck 1981–1988 (AMC-style VIN)',
            '1JU': 'Marmon Motor Company',
            '1L': 'Lincoln',
            '1L1': 'Lincoln car – limousine',
            '1L9_234': 'Laforza',
            '1LJ': 'Lincoln incomplete vehicle',
            '1LN': 'Lincoln car',
            '1LV': 'John Deere equipment designed in Augusta, Georgia',
            '1M0': 'John Deere Gator',
            '1M1': 'Mack Trucks',
            '1M2': 'Mack Trucks',
            '1M8': 'Motor Coach Industries',
            '1M9_682': 'Mosler Automotive',
            '1M9_816': 'Proterra Through mid-2019',
            '1MB': 'Mercedes-Benz Truck Co.',
            '1ME': 'Mercury car',
            '1MR': 'Continental Mark VI & VII 1981–1985 & Continental sedan 1982–1985',
            '1N4': 'Nissan car',
            '1N6': 'Nissan truck',
            '1N9_013': 'Neoplan USA',
            '1N9_393': 'Nikola Corporation',
            '1NK': 'Kenworth incomplete vehicle',
            '1NP': 'Peterbilt incomplete vehicle',
            '1NX': 'Toyota car made by NUMMI',
            '1P3': 'Plymouth car',
            '1P4': 'Plymouth MPV/SUV',
            '1P9_213': 'Panoz',
            '1PY': 'John Deere equipment designed or manufactured in Pune, India',
            '1S9_098': 'Scania AB Scania CN112 bus made in Orange, CT',
            '1S9_842': 'Saleen S7',
            '1S9_944': 'SSC North America',
            '1T7': 'Thomas Built Buses',
            '1T8': 'Thomas Built Buses',
            '1T9_899': 'Tomcar USA',
            '1TU': 'Transportation Manufacturing Corporation',
            '1UT': 'Jeep DJ made by AM General',
            '1V1': 'Volkswagen truck',
            '1V2': 'Volkswagen SUV',
            '1V9_048': 'Vector Aeromotive',
            '1VH': 'Orion Bus Industries',
            '1VR': 'Vermeer Corporation',
            '1VW': 'Volkswagen car',
            '1WU': 'White truck',
            '1WV': 'Winnebago Industries',
            '1WW': 'Winnebago Industries',
            '1WX': 'White incomplete vehicle',
            '1WY': 'White incomplete vehicle',
            '1XK': 'Kenworth truck',
            '1XM': 'Renault Alliance/GTA/Encore 1984–1987',
            '1XP': 'Peterbilt truck',
            '1Y1': 'Chevrolet/Geo car made by NUMMI',
            '1YJ': 'Rokon International, Inc.',
            '1YV': 'Mazda',
            '1Z3': 'Mitsubishi Raider',
            '1Z7': 'Mitsubishi Raider',
            '1Z9_332': 'Oshkosh Specialty Vehicles LLC',
            '1ZV': 'Ford made by AutoAlliance International',
            '1ZW': 'Mercury made by AutoAlliance International',
            '10R': 'E-Z-GO',
            '10T': 'Oshkosh Corporation',
            '12A': 'Avanti',
            '137': 'AM General Hummer & Hummer H1',
            '15G': 'Gillig bus',
            '16X': 'Vixen 21 motorhome',
            '17N': 'John Deere incomplete vehicle (RV chassis)',
            '19U': 'Acura car made by Honda of America Mfg. in Ohio',
            '19V': 'Acura car made by Honda Manufacturing of Indiana',
            '19X': 'Honda car made by Honda Manufacturing of Indiana',
        },

        // Canada
        'Canada': {
            '2A3': 'Imperial (<500 units)',
            '2A4': 'Chrysler brand MPV/SUV 2006–2011 only',
            '2A8': 'Chrysler brand MPV/SUV 2006–2011 only',
            '2AY': 'Hino',
            '2AZ': 'Hino',
            '2B1': 'Orion Bus Industries',
            '2B3': 'Dodge car 1981–2011',
            '2B4': 'Dodge MPV 1981–2002',
            '2B5': 'Dodge "bus" (van with more than 3 rows of seats) 1981–2002',
            '2B6': 'Dodge incomplete vehicle 1981–2002',
            '2B7': 'Dodge truck 1981–2002',
            '2BC': 'Jeep Wrangler (YJ) 1987–1988 (using AMC-style VIN structure)',
            '2BP': 'Ski-Doo',
            '2BV': 'Can-Am & Bombardier ATV',
            '2BW': 'Can-Am Commander E LSV',
            '2BX': 'Can-Am Spyder',
            '2BZ': 'Can-Am Freedom Trailer for Can-Am Spyder',
            '2C1': 'Geo/Chevrolet car made by CAMI Automotive',
            '2C3': 'Chrysler brand car 1981–2011; Chrysler Group (all brands) car (including Lancia) 2012–',
            '2C4': 'Chrysler brand MPV/SUV 2000–2005; Chrysler Group (all brands) MPV (including Lancia & VW) 2012–',
            '2C7': 'Pontiac car made by CAMI Automotive (only sold by GM Canada)',
            '2C8': 'Chrysler brand MPV/SUV 2001–2005',
            '2C9_145': 'Campagna Motors (145) (<500 units)',
            '2CC': 'American Motors Corporation MPV',
            '2CG': 'Asüna / Pontiac SUV made by CAMI Automotive (only sold by GM Canada)',
            '2CK': 'GMC Tracker SUV made by CAMI Automotive (1990–1991); Pontiac Torrent SUV made by CAMI Automotive (2006–2009)',
            '2CM': 'American Motors Corporation car',
            '2CN': 'Geo / Chevrolet SUV made by CAMI Automotive (1990–2011)',
            '2CT': 'GMC Terrain SUV made by CAMI Automotive (2010–2011)',
            '2D4': 'Dodge MPV 2003–2011 only',
            '2D6': 'Dodge incomplete vehicle 2003',
            '2D7': 'Dodge truck 2003',
            '2D8': 'Dodge MPV 2003–2011 only',
            '2DG': 'Ontario Drive & Gear (<500 units)',
            '2E3': 'Eagle car 1989–1997 (using Chrysler-style VIN structure)',
            '2E4': 'Lancia MPV',
            '2F': 'Ford',
            '2FA': 'Ford car',
            '2FM': 'Ford MPV/SUV',
            '2FT': 'Ford truck',
            '2FU': 'Freightliner Trucks',
            '2FV': 'Freightliner Trucks',
            '2FW': 'Sterling Trucks (truck)',
            '2FY': 'New Flyer',
            '2FZ': 'Sterling Trucks (incomplete vehicle)',
            '2G': 'General Motors',
            '2G0': 'GMC "bus" (van with more than 3 rows of seats) 1981–1986; Opel car 2007–2017',
            '2G1': 'Chevrolet',
            '2G2': 'Pontiac',
            '2G3': 'Oldsmobile',
            '2G4': 'Buick',
            '2G5': 'GMC MPV 1981–1986; BrightDrop Zevo delivery van',
            '2G6': 'Cadillac',
            '2G7': 'Pontiac (sold only by GM Canada)',
            '2G8': 'Chevrolet MPV 1981–1986',
            '2G9': 'Gnome Homes (<500 units)',
            '2GA': 'Chevrolet "bus" (van with more than 3 rows of seats)',
            '2GB': 'Chevrolet (incomplete vehicles)',
            '2GC': 'Chevrolet (truck)',
            '2GD': 'GMC (incomplete vehicles)',
            '2GE': 'Cadillac (incomplete vehicle)',
            '2GH': 'GMC GM New Look bus & GM Classic series bus',
            '2GJ': 'GMC "bus" (van with more than 3 rows of seats) 1987–',
            '2GK': 'GMC MPV/SUV 1987–',
            '2GN': 'Chevrolet MPV/SUV 1987–',
            '2GT': 'GMC (truck)',
            '2HG': 'Honda car made by Honda of Canada Manufacturing',
            '2HH': 'Acura car made by Honda of Canada Manufacturing',
            '2HJ': 'Honda truck made by Honda of Canada Manufacturing',
            '2HK': 'Honda MPV/SUV made by Honda of Canada Manufacturing',
            '2HM': 'Hyundai',
            '2HN': 'Acura SUV made by Honda of Canada Manufacturing',
            '2HS': 'International Trucks (truck)',
            '2HT': 'International Trucks (incomplete vehicle)',
            '2J4': 'Jeep Wrangler (YJ) 1989–1992 (using Chrysler-style VIN structure)',
            '2L1': 'Lincoln (incomplete vehicle – limo)',
            '2L9': 'Les Contenants Durabac (<500 units)',
            '2LJ': 'Lincoln (incomplete vehicle – hearse)',
            '2LM': 'Lincoln SUV',
            '2LN': 'Lincoln (car)',
            '2M1': 'Mack Trucks',
            '2M2': 'Mack Trucks',
            '2ME': 'Mercury (car)',
            '2MG': 'Motor Coach Industries (produced from Sept. 1, 2008 on)',
            '2MR': 'Mercury (MPV)',
            '2NK': 'Kenworth (incomplete vehicle)',
            '2NP': 'Peterbilt (incomplete vehicle)',
            '2NV': 'Nova Bus',
            '2P3': 'Plymouth (car)',
            '2P4': 'Plymouth (MPV) 1981–2000',
            '2P5': 'Plymouth "bus" (van with more than 3 rows of seats) 1981–1983',
            '2P9_001': 'Prevost 1981–1995 (<500 units)',
            '2PC': 'Prevost 1996–',
            '2S2': 'Suzuki car made by CAMI Automotive',
            '2S3': 'Suzuki SUV made by CAMI Automotive',
            '2T1': 'Toyota (car)',
            '2T2': 'Lexus (SUV)',
            '2T3': 'Toyota (SUV)',
            '2V4': 'Volkswagen Routan',
            '2V8': 'Volkswagen Routan',
            '2WK': 'Western Star Trucks (truck)',
            '2WL': 'Western Star Trucks (incomplete vehicle)',
            '2WM': 'Western Star Trucks (incomplete vehicle)',
            '2XK': 'Kenworth (truck)',
            '2XM': 'Eagle Premier (1988 only; AMC-style VIN structure)',
            '2XP': 'Peterbilt (truck)',
        },

        // Mexico
        'Mexico': {
            '3A4': 'Chrysler brand MPV 2006–2010 only',
            '3A8': 'Chrysler brand MPV 2006–2010 only',
            '3AK': 'Freightliner Trucks',
            '3AL': 'Freightliner Trucks',
            '3AV': 'BMW Mexico 1999–2009',
            '3B3': 'Dodge car 1981–2011',
            '3B4': 'Dodge SUV 1986–1993',
            '3B6': 'Dodge incomplete vehicle 1981–2002',
            '3B7': 'Dodge truck 1981–2002',
            '3BJ': 'Western Star 3700 truck made by DINA S.A.',
            '3BK': 'Kenworth incomplete vehicle',
            '3BM': 'Motor Coach Industries bus made by DINA S.A.',
            '3BP': 'Peterbilt incomplete vehicle',
            '3C3': 'Chrysler brand car 1981–2011; Chrysler Group (all brands) car (including Fiat) 2012–',
            '3C4': 'Chrysler brand MPV 2001–2005; Chrysler Group (all brands) MPV (including Fiat) 2012–',
            '3C6': 'Chrysler Group (all brands) truck 2012–',
            '3C7': 'Chrysler Group (all brands) incomplete vehicle 2012–',
            '3C8': 'Chrysler brand MPV 2001–2005',
            '3CE': 'Volvo Buses de Mexico',
            '3CZ': 'Honda SUV',
            '3D2': 'Dodge incomplete vehicle 2007–2009',
            '3D3': 'Dodge truck 2006–2009',
            '3D4': 'Dodge SUV 2009–2011',
            '3D6': 'Dodge incomplete vehicle 2003–2011',
            '3D7': 'Dodge truck 2002–2011',
            '3E4': 'Fiat SUV',
            '3F': 'Ford',
            '3F6': 'Sterling Bullet',
            '3FA': 'Ford car',
            '3FC': 'Ford stripped chassis made by Ford & IMMSA',
            '3FM': 'Ford MPV/SUV',
            '3FN': 'Ford F-650/F-750 made by Blue Diamond Truck Co.',
            '3FR': 'Ford F-650/F-750 made by Blue Diamond Truck Co.',
            '3FT': 'Ford truck',
            '3G': 'General Motors',
            '3G0': 'Saab 9-4X 2011; Holden Equinox 2018–2020',
            '3G1': 'Chevrolet car',
            '3G2': 'Pontiac car',
            '3G4': 'Buick car',
            '3G5': 'Buick SUV',
            '3G7': 'Pontiac SUV',
            '3GC': 'Chevrolet truck',
            '3GK': 'GMC SUV',
            '3GM': 'Holden Suburban',
            '3GN': 'Chevrolet SUV',
            '3GS': 'Saturn SUV',
            '3GT': 'GMC truck',
            '3GY': 'Cadillac SUV',
            '3H1': 'Honda motorcycle/UTV',
            '3H3': 'Hyundai de Mexico, S.A. de C.V. for Hyundai Translead (truck trailers)',
            '3HA': 'International Trucks incomplete vehicle',
            '3HC': 'International Trucks truck',
            '3HG': 'Honda car',
            '3HS': 'International Trucks & Caterpillar Trucks truck',
            '3HT': 'International Trucks & Caterpillar Trucks incomplete vehicle',
            '3JB': 'Can-Am ATV/UTV & Can-Am Ryker',
            '3KP': 'Kia/Hyundai car',
            '3LN': 'Lincoln car',
            '3MD': 'Mazda car',
            '3ME': 'Mercury car',
            '3MV': 'Mazda SUV',
            '3MW': 'BMW',
            '3MY': 'Toyota car made by Mazda de Mexico Vehicle Operation',
            '3MZ': 'Mazda car',
            '3N1': 'Nissan car',
            '3N6': 'Nissan truck & Chevrolet City Express',
            '3N8': 'Nissan MPV',
            '3NE': 'Polaris Inc. ATV',
            '3NS': 'Polaris Inc. UTV',
            '3P3': 'Plymouth car',
            '3PC': 'Infiniti SUV made by COMPAS',
            '3TM': 'Toyota truck made by TMMBC',
            '3TY': 'Toyota truck made by TMMGT',
            '3VV': 'Volkswagen SUV',
            '3VW': 'Volkswagen car',
            '3WK': 'Kenworth truck',
            '3WP': 'Peterbilt truck',
        },

        // United States
        'United States': {
            '4A3': 'Mitsubishi Motors car',
            '4A4': 'Mitsubishi Motors SUV',
            '4B3': 'Dodge car made by Diamond-Star Motors factory',
            '4B9_038': 'BYD Coach & Bus LLC',
            '4C3': 'Chrysler car made by Diamond-Star Motors factory',
            '4C9_561': 'Czinger',
            '4CD': 'Oshkosh Chassis Division incomplete vehicle (RV chassis)',
            '4DR': 'IC Bus',
            '4E3': 'Eagle car made by Diamond-Star Motors factory',
            '4F2': 'Mazda SUV made by Ford',
            '4F4': 'Mazda truck made by Ford',
            '4G1': 'Chevrolet Cavalier convertible made by Genasys L.C. (GM/ASC)',
            '4G2': 'Pontiac Sunfire convertible made by Genasys L.C. (GM/ASC)',
            '4G3': 'Toyota Cavalier made by GM',
            '4G5': 'General Motors EV1',
            '4GD': 'WhiteGMC Brigadier 1988–1989 made by GM; Opel Sintra',
            '4GL': 'Buick incomplete vehicle',
            '4GT': 'Isuzu incomplete vehicle built by GM',
            '4JG': 'Mercedes-Benz SUV',
            '4KB': 'Chevrolet W-Series incomplete vehicle (gas engine only)',
            '4KD': 'GMC W-Series incomplete vehicle (gas engine only)',
            '4KL': 'Isuzu commercial truck built by GM',
            '4M2': 'Mercury MPV/SUV',
            '4ML': 'Oshkosh Trailer Division',
            '4MZ': 'Buell Motorcycle Company',
            '4N2': 'Nissan Quest made by Ford',
            '4NU': 'Isuzu Ascender made by GM',
            '4P1': 'Pierce Manufacturing',
            '4P3': 'Plymouth car made by Diamond-Star Motors factory 1990–1994; Mitsubishi Motors SUV 2013–2015 (export only)',
            '4RK': 'Nova Bus & Prevost made by Nova Bus (US) Inc.',
            '4S1': 'Isuzu truck made by Subaru Isuzu Automotive',
            '4S2': 'Isuzu SUV made by Subaru Isuzu Automotive',
            '4S3': 'Subaru car',
            '4S4': 'Subaru SUV/MPV',
            '4S6': 'Honda SUV made by Subaru Isuzu Automotive',
            '4S7': 'Spartan Motors incomplete vehicle',
            '4S9_197': 'Smith Electric Vehicles US Corp.',
            '4S9_419': 'Spartan Motors truck',
            '4S9_454': 'Scuderia Cameron Glickenhaus car',
            '4S9_542': 'Scuderia Cameron Glickenhaus SCG Boot (MPV)',
            '4S9_544': 'Scuderia Cameron Glickenhaus car',
            '4S9_559': 'Spartan Fire, LLC truck (formerly Spartan ER)',
            '4S9_560': 'Spartan Fire, LLC incomplete vehicle (formerly Spartan ER)',
            '4T1': 'Toyota car made by Toyota Motor Manufacturing Kentucky',
            '4T3': 'Toyota MPV/SUV made by Toyota Motor Manufacturing Kentucky',
            '4T4': 'Toyota car made by Subaru of Indiana Automotive',
            '4T9_208': 'Xos, Inc.',
            '4TA': 'Toyota truck made by NUMMI',
            '4UF': 'Arctic Cat',
            '4US': 'BMW car',
            '4UZ': 'Freightliner Custom Chassis Corporation; Mitsubishi Fuso gas trucks; Thomas Built Buses FS-65 & Saf-T-Liner C2',
            '4V1': 'WhiteGMC truck',
            '4V2': 'WhiteGMC incomplete vehicle',
            '4V4': 'Volvo Trucks North America truck',
            '4V5': 'Volvo Trucks North America incomplete vehicle',
            '4VA': 'Volvo Trucks North America truck',
            '4VG': 'Volvo Trucks North America truck',
            '4VE': 'Volvo Trucks North America incomplete vehicle',
            '4VH': 'Volvo Trucks North America incomplete vehicle',
            '4VM': 'Volvo Trucks North America incomplete vehicle',
            '4VZ': 'Spartan Motors/The Shyft Group incomplete vehicle (bare chassis)',
            '4XA': 'Polaris Inc.',
            '4YM': 'Carry-On Trailer, Inc.',
            '4Z3': 'American LaFrance truck',
            '43C': 'Consulier',
            '46G': 'Gillig incomplete vehicle',
            '478': 'Honda ATV',
            '480': 'Sterling Trucks truck',
            '49H': 'Sterling Trucks incomplete vehicle',
            '5AS': 'GEM',
            '5B4': 'Workhorse Custom Chassis incomplete vehicle (RV chassis)',
            '5BZ': 'Nissan van (more than 3 rows of seats)',
            '5CD': 'Indian Motorcycle Company of America (Gilroy, CA)',
            '5CX': 'Shelby Series 1',
            '5DF': 'Thomas Dennis Company LLC',
            '5EH': 'Excelsior-Henderson Motorcycle',
            '5FN': 'Honda MPV/SUV made by Honda Manufacturing of Alabama',
            '5FP': 'Honda truck made by Honda Manufacturing of Alabama',
            '5FR': 'Acura SUV made by Honda Manufacturing of Alabama',
            '5FY': 'New Flyer',
            '5G8': 'Holden Volt',
            '5GA': 'Buick MPV/SUV',
            '5GD': 'Daewoo G2X',
            '5GN': 'Hummer H3T',
            '5GR': 'Hummer H2',
            '5GT': 'Hummer H3',
            '5GZ': 'Saturn MPV/SUV',
            '5HD': 'Harley-Davidson for export markets',
            '5J6': 'Honda SUV made by Honda of America Mfg. (Ohio)',
            '5J8': 'Acura SUV made by Honda of America Mfg. (Ohio)',
            '5KB': 'Honda car made by Honda Manufacturing of Alabama',
            '5KJ': 'Western Star Trucks truck',
            '5KK': 'Western Star Trucks truck',
            '5L1': 'Lincoln SUV (2004–2009)',
            '5LD': 'Ford & Lincoln incomplete vehicle – limousine (2010–2014)',
            '5LM': 'Lincoln SUV',
            '5LT': 'Lincoln truck',
            '5MZ': 'Buell Motorcycle Company for export markets',
            '5N1': 'Nissan & Infiniti SUV',
            '5N3': 'Infiniti SUV',
            '5NM': 'Hyundai SUV',
            '5NP': 'Hyundai car',
            '5NT': 'Hyundai truck',
            '5PV': 'Hino incomplete vehicle',
            '5S3': 'Saab 9-7X',
            '5SA': 'Suzuki ATV',
            '5SX': 'American LaFrance incomplete vehicle (Condor)',
            '5TB': 'Toyota truck made by TMMI',
            '5TD': 'Toyota MPV/SUV made by TMMI',
            '5TE': 'Toyota truck made by NUMMI',
            '5TF': 'Toyota truck made by TMMTX',
            '5UM': 'BMW M car',
            '5UX': 'BMW SUV',
            '5VC': 'Autocar incomplete vehicle',
            '5VP': 'Victory Motorcycles',
            '5WE': 'IC Bus incomplete vehicle',
            '5XX': 'Kia car',
            '5XY': 'Kia/Hyundai SUV',
            '5Y2': 'Pontiac Vibe made by NUMMI',
            '5Y4': 'Yamaha Motor Company ATV/UTV',
            '5YA': 'Indian Motorcycle Company (Kings Mountain, NC)',
            '5YF': 'Toyota car made by TMMMS',
            '5YJ': 'Tesla',
            '5YM': 'BMW M SUV',
            '5Z6': 'Suzuki truck made by Nissan',
            '50E': 'Lucid Motors',
            '50G': 'Karma Automotive',
            '516': 'Autocar truck',
            '51R': 'Brammo Motorcycles',
            '523': 'VPG',
            '52C': 'GEM (subsidiary of Polaris Inc.)',
            '538': 'Zero Motorcycles',
            '53G': 'Coda Automotive',
            '53T': 'Think North America (Elkhart, IN)',
            '546': 'EBR',
            '54C': 'Winnebago Industries trailer',
            '54D': 'Isuzu & Chevrolet commercial trucks built by Spartan Motors/The Shyft Group',
            '55S': 'Mercedes-Benz car',
            '56K': 'Indian Motorcycle International (Polaris subsidiary)',
            '57W': 'Mobility Ventures',
            '57X': 'Polaris Slingshot',
            '58A': 'Lexus car made by TMMK',
        },
    },

    /**
     * Oceania
     */
    Oceania : {
        // Australia
        'Australia': {
            '6F1': 'Ford',
            '6F2': 'Iveco Trucks Australia Ltd.',
            '6F4': 'Nissan Motor Australia',
            '6F5': 'Kenworth Australia',
            '6FM': 'Mack Trucks Australia',
            '6FP': 'Ford',
            '6G': 'General Motors',
            '6G1': 'Holden & Chevrolet',
            '6G2': 'Pontiac',
            '6G3': 'Chevrolet',
            '6H': 'Holden',
            '6MM': 'Mitsubishi',
            '6MP': 'Mercury Capri',
            '6T1': 'Toyota',
            '6T9': 'Trailer',
            '6U9': 'Low Volume (Grey) Imports – Non-ISO VIN format (e.g., PV35-400637 → 6U90000PV35400637)',
            '6ZZ': 'Low Volume (Grey) Imports – Non-ISO VIN format (e.g., PV35-400637 → 6ZZ0000PV35400637)',
        },

        // New Zealand
        'New Zealand': {
            '7A1': 'Mitsubishi',
            '7A3': 'Honda',
            '7A4': 'Toyota',
            '7A5': 'Ford',
            '7A7': 'Nissan New Zealand',
            '7A8': 'NZ Transport Agency (pre-2009)',
            '7AT': 'NZ Transport Agency (post-2009)',
        },
    },

    /**
     * North America
     */
    NorthAmerica : {
        // United States
        'United States': {
            '7FA': 'Honda SUV made by Honda Manufacturing of Indiana',
            '7FC': 'Rivian truck',
            '7GZ': 'GMC incomplete vehicles made by Navistar International',
            '7G2': 'Tesla Cybertruck & Tesla Semi',
            '7H4': 'Hino truck',
            '7JR': 'Volvo Cars car',
            '7JZ': 'Proterra (from mid-2019)',
            '7KG': 'Vanderhall Motor Works',
            '7MM': 'Mazda SUV made by MTMUS (Mazda-Toyota Joint Venture)',
            '7MU': 'Toyota SUV made by MTMUS (Mazda-Toyota Joint Venture)',
            '7NA': 'Navistar Defense',
            '7NY': 'Lordstown Motors',
            '7PD': 'Rivian SUV',
            '7RZ': 'Electric Last Mile Solutions',
            '7R4': 'Icon Electric Vehicles',
            '7SA': 'Tesla SUV (2022+)',
            '7SU': 'Blue Arc electric trucks made by The Shyft Group',
            '7SV': 'Toyota SUV made by TMMTX',
            '7SX': 'Global Electric Motorcars',
            '7Z0': 'Zoox',
        },
    },

    /**
     * South America
     */
    SouthAmerica : {
        // Argentina
        'Argentina': {
            '8AC': 'Mercedes-Benz vans (for South America)',
            '8AD': 'Peugeot',
            '8AE': 'Peugeot van',
            '8AF': 'Ford Motor Argentina',
            '8AG': 'General Motors de Argentina (Chevrolet)',
            '8AJ': 'Toyota Argentina',
            '8AN': 'Nissan',
            '8AP': 'Fiat',
            '8AT': 'Iveco',
            '8AW': 'Volkswagen Argentina',
            '8A1': 'Renault Argentina',
            '8A3': 'Scania Argentina',
            '8BB': 'Agrale Argentina S.A.',
            '8BC': 'Citroën',
            '8BN': 'Mercedes-Benz incomplete vehicle (North America)',
            '8BR': 'Mercedes-Benz "bus" (van with more than 3 rows of seats) (North America)',
            '8BT': 'Mercedes-Benz MPV (van with 2 or 3 rows of seats) (North America)',
            '8BU': 'Mercedes-Benz truck (cargo van with 1 row of seats) (North America)',
            '8CH': 'Honda motorcycle',
            '8C3': 'Honda car/SUV',
        },  

        // Chile
        'Chile': {
            '8F9': 'Reborn Electric Motors SPA',
            '8G1': 'Automotores Franco Chilena S.A. (Renault)',
            '8GD': 'Automotores Franco Chilena S.A. (Peugeot)',
            '8GG': 'General Motors Chile Ltda.',
        },

        // Ecuador
        'Ecuador': {
            '8L4': 'Great Wall Motors made by Ciudad del Auto Ciauto Cia. Ltda.',
            '8LB': 'General Motors OBB',
            '8LF': 'Maresa (Mazda)',
            '8LG': 'Aymesa (Hyundai Motor & Kia)',
        },

        // Venezuela
        'Venezuela': {
            '8XD': 'Ford Motor Venezuela',
            '8XJ': 'Mack de Venezuela C.A.',
            '8XV': 'Iveco Venezuela C.A.',
            '8Z1': 'General Motors Venezolana C.A.',
        },

        // Bolivia
        'Bolivia': {
            '829': 'Quantum Motors',
        },

        // Brazil
        'Brazil': {
            '9AM': 'Massari (?)',
            '9BD': 'Fiat Automóveis',
            '9BF': 'Ford Brasil',
            '9BG': 'General Motors do Brasil (Chevrolet)',
            '9BH': 'Hyundai Motor Brasil',
            '9BM': 'Mercedes-Benz (car, SUV & commercial truck)',
            '9BN': 'Mafersa',
            '9BR': 'Toyota',
            '9BS': 'Scania Brazil',
            '9BV': 'Volvo Trucks',
            '9BW': 'Volkswagen do Brasil',
            '9BY': 'Agrale S.A.',
            '9C2': 'Honda Motorcycles',
            '9C6': 'Yamaha Motor',
            '9CD': 'Suzuki motorcycles assembled by J. Toledo Motos do Brasil',
            '9DW': 'Kenworth & Peterbilt trucks made by Volkswagen do Brasil',
            '9EZ': 'Homebuilt vehicles',
            '932': 'Harley-Davidson',
            '935': 'Citroën',
            '936': 'Peugeot',
            '937': 'Dodge',
            '93C': 'General Motors do Brasil Chevrolet SUV (Mexico)',
            '93H': 'Honda car/SUV',
            '93K': 'Volvo Trucks',
            '93P': 'Volare',
            '93S': 'Navistar International',
            '93U': 'Audi 1999–2006',
            '93V': 'Navistar International',
            '93W': 'Fiat Ducato made by Iveco 2000–2016',
            '93X': 'Souza Ramos – Mitsubishi Motors / Suzuki Jimny',
            '93Y': 'Renault do Brasil',
            '93Z': 'Iveco',
            '94D': 'Nissan',
            '94G': 'Indabra',
            '94M': 'HVR-Busscar',
            '94N': 'RWM Brazil',
            '94T': 'Troller Veículos Especiais',
            '953': 'VW Truck & Bus / MAN Truck & Bus',
            '95P': 'CAOA / Hyundai & CAOA Chery',
            '95V': 'Dafra Motos (motorscooters from SYM) & Ducati, KTM, & MV Agusta assembled by Dafra',
            '95V': 'BMW motorcycles assembled by Dafra Motos 2009–2016',
            '95Z': 'Buell Motorcycle Company assembled by Harley-Davidson Brazil',
            '96P': 'Kawasaki',
            '97N': 'Triumph Motorcycles Ltd',
            '988': 'Jeep and Fiat (made at the Goiana plant)',
            '98M': 'BMW car/SUV',
            '98R': 'Chery',
            '99A': 'Audi 2016-',
            '99J': 'Jaguar Land Rover',
            '99K': 'Haojue & Kymco assembled by JTZ Indústria e Comércio de Motos',
            '99L': 'BYD',
            '99Z': 'BMW Motorrad Motorcycle assembled by BMW 2017-',
        },

        // Colombia
        'Colombia': {
            '9FB': 'Sofasa (Renault)',
            '9FC': 'Compañía Colombiana Automotriz S.A. (Mazda)',
            '9GA': 'GM Colmotores S.A. (Chevrolet)',
        },

        // Uruguay
        'Uruguay': {
            '9UJ': 'Chery assembled by Chery Socma S.A.',
            '9UK': 'Lifan',
            '9UW': 'Kia made by Nordex S.A.',
            '9V7': 'Citroen made by Nordex S.A.',
            '9V8': 'Peugeot made by Nordex S.A.',
        },
    },
};

// Make it accessible globally for non-module scripts (browser only)
if (typeof window !== 'undefined') {
  window.MANUFACTURERS = MANUFACTURERS;
}